package com.IndieBrokers.view;

import com.IndieBrokers.controller.ValidationUtil;
import java.awt.Color;
import java.util.List;
import com.IndieBrokers.model.IndieBrokersModel;
import java.util.LinkedList;
import javax.swing.table.DefaultTableModel;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JTextField;


/**
/**
 *
 * @author ampho
 */
public class IndieBrokersApp extends javax.swing.JFrame {

    private List<IndieBrokersModel> BrokersList;
    private java.awt.CardLayout cardLayout;
    private final ValidationUtil validationUtil;
    private final Color errorColor = new Color(255, 51, 0);
    private final Color yellowColor = new Color(189, 244, 255);
    /**
     * Creates new form IndieBrokersApp
     */
    public IndieBrokersApp() {
        initComponents();
        validationUtil = new ValidationUtil();
        initializeLayout();
        initializeData();// Set up CardLayout and add screens
        startProgress(); // Show loading screen and initiate progress 
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        IndieLoginScreen = new javax.swing.JPanel();
        jPanel5 = new javax.swing.JPanel();
        jPanel6 = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        UsernameField = new javax.swing.JTextField();
        PasswordField = new javax.swing.JPasswordField();
        LoginButton = new javax.swing.JButton();
        loginErrorLabel = new javax.swing.JLabel();
        IndieMainScreen = new javax.swing.JPanel();
        upperbar = new javax.swing.JPanel();
        indienamelbl = new javax.swing.JLabel();
        logolbl = new javax.swing.JLabel();
        LogoutButton = new javax.swing.JButton();
        tabPaneMain5 = new javax.swing.JTabbedPane();
        pnlHome5 = new javax.swing.JPanel();
        jLabel24 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
        IndieBrokersList = new javax.swing.JPanel();
        BrokerListTable = new javax.swing.JScrollPane();
        BrokerTable = new javax.swing.JTable();
        lblTblStudentTitle = new javax.swing.JLabel();
        BrokerIDfield = new javax.swing.JTextField();
        BrokerNameField = new javax.swing.JTextField();
        ContactField = new javax.swing.JTextField();
        BankField = new javax.swing.JTextField();
        AddButton = new javax.swing.JButton();
        UpdateButton = new javax.swing.JButton();
        DltButton = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        BrokerIDerrorLabel = new javax.swing.JLabel();
        BrokerNameerrorLabel = new javax.swing.JLabel();
        ContacterrorLabel = new javax.swing.JLabel();
        BankNameerrorLabel = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        ExperienceerrorLabel = new javax.swing.JLabel();
        ExperienceTextFields = new javax.swing.JTextField();
        CollateralField = new javax.swing.JTextField();
        jLabel23 = new javax.swing.JLabel();
        CollateralerrorLabel = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        pnlAboutUs = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTextArea2 = new javax.swing.JTextArea();
        IndieLoadingScreen = new javax.swing.JPanel();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        pgBarSplashScreen = new javax.swing.JProgressBar(0,100);

        IndieLoginScreen.setPreferredSize(new java.awt.Dimension(809, 495));

        jPanel5.setBackground(new java.awt.Color(189, 244, 255));

        jPanel6.setBackground(new java.awt.Color(213, 244, 255));

        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/IndieBrokers/resources/Indie_logo_1.png"))); // NOI18N

        jLabel12.setBackground(new java.awt.Color(0, 155, 255));
        jLabel12.setFont(new java.awt.Font("Poppins Medium", 0, 36)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(0, 155, 255));
        jLabel12.setText("Indie");

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGap(357, 357, 357)
                .addComponent(jLabel8)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel12)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(12, Short.MAX_VALUE))
        );

        jLabel13.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/IndieBrokers/resources/Indie Home Design (1).png"))); // NOI18N

        jLabel14.setFont(new java.awt.Font("Poppins Medium", 0, 36)); // NOI18N
        jLabel14.setText("Login Now");

        jLabel15.setFont(new java.awt.Font("Poppins", 0, 18)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(77, 77, 77));
        jLabel15.setText("Continue to just grow the grown");

        jLabel16.setFont(new java.awt.Font("Poppins Medium", 0, 18)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(77, 77, 77));
        jLabel16.setText("Username :");

        jLabel17.setFont(new java.awt.Font("Poppins Medium", 0, 18)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(77, 77, 77));
        jLabel17.setText("Password :");

        UsernameField.setFont(new java.awt.Font("Poppins", 0, 12)); // NOI18N
        UsernameField.setForeground(new java.awt.Color(77, 77, 77));
        UsernameField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                UsernameFieldActionPerformed(evt);
            }
        });

        PasswordField.setForeground(new java.awt.Color(77, 77, 77));
        PasswordField.setMinimumSize(new java.awt.Dimension(64, 25));
        PasswordField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PasswordFieldActionPerformed(evt);
            }
        });

        LoginButton.setBackground(new java.awt.Color(0, 151, 255));
        LoginButton.setFont(new java.awt.Font("Poppins", 0, 14)); // NOI18N
        LoginButton.setForeground(new java.awt.Color(255, 255, 255));
        LoginButton.setText("Login");
        LoginButton.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        LoginButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LoginButtonActionPerformed(evt);
            }
        });

        loginErrorLabel.setBackground(new java.awt.Color(255, 0, 0));
        loginErrorLabel.setFont(new java.awt.Font("Poppins Medium", 0, 12)); // NOI18N
        loginErrorLabel.setForeground(new java.awt.Color(255, 0, 0));

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addComponent(jLabel13)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 67, Short.MAX_VALUE)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                        .addComponent(jLabel14)
                        .addGap(95, 95, 95))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel15)
                            .addGroup(jPanel5Layout.createSequentialGroup()
                                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel16)
                                    .addComponent(jLabel17))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(loginErrorLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(UsernameField)
                                        .addComponent(PasswordField, javax.swing.GroupLayout.PREFERRED_SIZE, 181, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                        .addGap(37, 37, 37))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                        .addComponent(LoginButton)
                        .addGap(125, 125, 125))))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 85, Short.MAX_VALUE)
                        .addComponent(jLabel13)
                        .addGap(99, 99, 99))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGap(51, 51, 51)
                        .addComponent(jLabel14)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel15)
                        .addGap(28, 28, 28)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel16)
                            .addComponent(UsernameField, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(34, 34, 34)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel17)
                            .addComponent(PasswordField, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(loginErrorLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(LoginButton)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );

        javax.swing.GroupLayout IndieLoginScreenLayout = new javax.swing.GroupLayout(IndieLoginScreen);
        IndieLoginScreen.setLayout(IndieLoginScreenLayout);
        IndieLoginScreenLayout.setHorizontalGroup(
            IndieLoginScreenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        IndieLoginScreenLayout.setVerticalGroup(
            IndieLoginScreenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        IndieMainScreen.setBackground(new java.awt.Color(189, 244, 255));
        IndieMainScreen.setMaximumSize(new java.awt.Dimension(809, 495));
        IndieMainScreen.setMinimumSize(new java.awt.Dimension(809, 495));
        IndieMainScreen.setPreferredSize(new java.awt.Dimension(809, 495));

        upperbar.setBackground(new java.awt.Color(213, 244, 255));

        indienamelbl.setBackground(new java.awt.Color(0, 155, 255));
        indienamelbl.setFont(new java.awt.Font("Poppins Medium", 0, 36)); // NOI18N
        indienamelbl.setForeground(new java.awt.Color(0, 155, 255));
        indienamelbl.setText("Indie");

        logolbl.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/IndieBrokers/resources/Indie_logo_1.png"))); // NOI18N

        LogoutButton.setBackground(new java.awt.Color(66, 11, 0));
        LogoutButton.setFont(new java.awt.Font("Poppins", 0, 12)); // NOI18N
        LogoutButton.setForeground(new java.awt.Color(255, 255, 255));
        LogoutButton.setText("Log out");
        LogoutButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LogoutButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout upperbarLayout = new javax.swing.GroupLayout(upperbar);
        upperbar.setLayout(upperbarLayout);
        upperbarLayout.setHorizontalGroup(
            upperbarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(upperbarLayout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(logolbl)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(indienamelbl)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(LogoutButton)
                .addGap(15, 15, 15))
        );
        upperbarLayout.setVerticalGroup(
            upperbarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(upperbarLayout.createSequentialGroup()
                .addGroup(upperbarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(upperbarLayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(upperbarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(logolbl, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(indienamelbl, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)))
                    .addGroup(upperbarLayout.createSequentialGroup()
                        .addGap(16, 16, 16)
                        .addComponent(LogoutButton)))
                .addContainerGap(9, Short.MAX_VALUE))
        );

        tabPaneMain5.setBackground(new java.awt.Color(189, 244, 255));
        tabPaneMain5.setFont(new java.awt.Font("Poppins", 1, 12)); // NOI18N

        pnlHome5.setBackground(new java.awt.Color(189, 244, 255));
        pnlHome5.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(234, 192, 32)));

        jLabel24.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/IndieBrokers/resources/Untitled-2.png"))); // NOI18N

        jLabel22.setFont(new java.awt.Font("Poppins", 1, 48)); // NOI18N
        jLabel22.setForeground(new java.awt.Color(32, 64, 118));
        jLabel22.setText("ITS TIME");

        jLabel25.setFont(new java.awt.Font("Poppins", 1, 24)); // NOI18N
        jLabel25.setForeground(new java.awt.Color(0, 105, 255));
        jLabel25.setText("Dive straight ahead into");

        jLabel26.setFont(new java.awt.Font("Poppins", 1, 24)); // NOI18N
        jLabel26.setForeground(new java.awt.Color(0, 105, 255));
        jLabel26.setText("Indie Brokers");

        javax.swing.GroupLayout pnlHome5Layout = new javax.swing.GroupLayout(pnlHome5);
        pnlHome5.setLayout(pnlHome5Layout);
        pnlHome5Layout.setHorizontalGroup(
            pnlHome5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlHome5Layout.createSequentialGroup()
                .addGroup(pnlHome5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlHome5Layout.createSequentialGroup()
                        .addGroup(pnlHome5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(pnlHome5Layout.createSequentialGroup()
                                .addGap(83, 83, 83)
                                .addComponent(jLabel25))
                            .addGroup(pnlHome5Layout.createSequentialGroup()
                                .addGap(148, 148, 148)
                                .addComponent(jLabel26)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 85, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlHome5Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jLabel22)
                        .addGap(134, 134, 134)))
                .addComponent(jLabel24, javax.swing.GroupLayout.PREFERRED_SIZE, 265, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(71, 71, 71))
        );
        pnlHome5Layout.setVerticalGroup(
            pnlHome5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlHome5Layout.createSequentialGroup()
                .addContainerGap(46, Short.MAX_VALUE)
                .addComponent(jLabel24, javax.swing.GroupLayout.PREFERRED_SIZE, 309, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(33, 33, 33))
            .addGroup(pnlHome5Layout.createSequentialGroup()
                .addGap(123, 123, 123)
                .addComponent(jLabel22)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel25)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel26)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        tabPaneMain5.addTab("Home", pnlHome5);

        IndieBrokersList.setBackground(new java.awt.Color(189, 244, 255));

        BrokerTable.setBackground(new java.awt.Color(0, 149, 183));
        BrokerTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Broker ID", "Broker Name", "Contact Num", "Bank Name", "Collateral", "Experience"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        BrokerTable.setGridColor(new java.awt.Color(0, 0, 0));
        BrokerTable.setSelectionBackground(new java.awt.Color(0, 0, 0));
        BrokerTable.setSelectionForeground(new java.awt.Color(255, 255, 255));
        BrokerTable.setShowGrid(true);
        BrokerTable.getTableHeader().setReorderingAllowed(false);
        BrokerListTable.setViewportView(BrokerTable);
        if (BrokerTable.getColumnModel().getColumnCount() > 0) {
            BrokerTable.getColumnModel().getColumn(0).setResizable(false);
            BrokerTable.getColumnModel().getColumn(1).setResizable(false);
            BrokerTable.getColumnModel().getColumn(2).setResizable(false);
            BrokerTable.getColumnModel().getColumn(3).setResizable(false);
            BrokerTable.getColumnModel().getColumn(4).setResizable(false);
            BrokerTable.getColumnModel().getColumn(5).setResizable(false);
        }

        lblTblStudentTitle.setBackground(new java.awt.Color(250, 250, 250));
        lblTblStudentTitle.setFont(new java.awt.Font("Poppins", 1, 14)); // NOI18N
        lblTblStudentTitle.setForeground(new java.awt.Color(66, 11, 0));
        lblTblStudentTitle.setText("Broker Information");

        BrokerIDfield.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        BrokerIDfield.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BrokerIDfieldActionPerformed(evt);
            }
        });

        BrokerNameField.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        BrokerNameField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BrokerNameFieldActionPerformed(evt);
            }
        });

        ContactField.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        ContactField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ContactFieldActionPerformed(evt);
            }
        });

        BankField.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        BankField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BankFieldActionPerformed(evt);
            }
        });

        AddButton.setBackground(new java.awt.Color(0, 149, 183));
        AddButton.setFont(new java.awt.Font("Poppins", 0, 18)); // NOI18N
        AddButton.setForeground(new java.awt.Color(255, 255, 255));
        AddButton.setText("Add");
        AddButton.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        AddButton.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        AddButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AddButtonActionPerformed(evt);
            }
        });

        UpdateButton.setBackground(new java.awt.Color(0, 149, 183));
        UpdateButton.setFont(new java.awt.Font("Poppins", 0, 18)); // NOI18N
        UpdateButton.setForeground(new java.awt.Color(255, 255, 255));
        UpdateButton.setText("Update");
        UpdateButton.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        UpdateButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                UpdateButtonActionPerformed(evt);
            }
        });

        DltButton.setBackground(new java.awt.Color(0, 149, 183));
        DltButton.setFont(new java.awt.Font("Poppins", 0, 18)); // NOI18N
        DltButton.setForeground(new java.awt.Color(255, 255, 255));
        DltButton.setText("Delete");
        DltButton.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        DltButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DltButtonActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Poppins", 0, 14)); // NOI18N
        jLabel2.setText("Broker ID:");

        jLabel3.setFont(new java.awt.Font("Poppins", 0, 14)); // NOI18N
        jLabel3.setText("Broker Name:");

        jLabel4.setFont(new java.awt.Font("Poppins", 0, 14)); // NOI18N
        jLabel4.setText("Contact No:");

        jLabel5.setFont(new java.awt.Font("Poppins", 0, 14)); // NOI18N
        jLabel5.setText("Bank Name:");

        BrokerIDerrorLabel.setFont(new java.awt.Font("Poppins", 0, 12)); // NOI18N
        BrokerIDerrorLabel.setForeground(new java.awt.Color(255, 0, 0));

        BrokerNameerrorLabel.setFont(new java.awt.Font("Poppins", 0, 12)); // NOI18N
        BrokerNameerrorLabel.setForeground(new java.awt.Color(255, 0, 0));

        ContacterrorLabel.setFont(new java.awt.Font("Poppins", 0, 12)); // NOI18N
        ContacterrorLabel.setForeground(new java.awt.Color(255, 0, 0));
        ContacterrorLabel.setToolTipText("");

        BankNameerrorLabel.setFont(new java.awt.Font("Poppins", 0, 12)); // NOI18N
        BankNameerrorLabel.setForeground(new java.awt.Color(255, 0, 0));

        jLabel21.setFont(new java.awt.Font("Poppins", 0, 14)); // NOI18N
        jLabel21.setText("Experience:");

        ExperienceerrorLabel.setFont(new java.awt.Font("Poppins", 0, 12)); // NOI18N
        ExperienceerrorLabel.setForeground(new java.awt.Color(255, 0, 0));

        ExperienceTextFields.setFont(new java.awt.Font("Poppins", 0, 12)); // NOI18N
        ExperienceTextFields.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        ExperienceTextFields.setPreferredSize(new java.awt.Dimension(64, 18));

        CollateralField.setBorder(javax.swing.BorderFactory.createTitledBorder(""));

        jLabel23.setFont(new java.awt.Font("Poppins", 0, 12)); // NOI18N
        jLabel23.setText("Collateral:");

        javax.swing.GroupLayout IndieBrokersListLayout = new javax.swing.GroupLayout(IndieBrokersList);
        IndieBrokersList.setLayout(IndieBrokersListLayout);
        IndieBrokersListLayout.setHorizontalGroup(
            IndieBrokersListLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, IndieBrokersListLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lblTblStudentTitle)
                .addGap(334, 334, 334))
            .addGroup(IndieBrokersListLayout.createSequentialGroup()
                .addGap(54, 54, 54)
                .addGroup(IndieBrokersListLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(IndieBrokersListLayout.createSequentialGroup()
                        .addGroup(IndieBrokersListLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, IndieBrokersListLayout.createSequentialGroup()
                                .addGroup(IndieBrokersListLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(BrokerIDfield, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(IndieBrokersListLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jLabel3)
                                    .addComponent(BrokerNameField, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(33, 33, 33)
                                .addGroup(IndieBrokersListLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(ContactField, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(ContacterrorLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(30, 30, 30)
                                .addGroup(IndieBrokersListLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(BankNameerrorLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(BankField, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(29, 29, 29))
                            .addGroup(IndieBrokersListLayout.createSequentialGroup()
                                .addComponent(BrokerIDerrorLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(BrokerNameerrorLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                        .addGroup(IndieBrokersListLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(ExperienceerrorLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel21)
                            .addComponent(ExperienceTextFields, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(23, 23, 23)
                        .addGroup(IndieBrokersListLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(CollateralField, javax.swing.GroupLayout.DEFAULT_SIZE, 84, Short.MAX_VALUE)
                            .addComponent(jLabel23)
                            .addComponent(CollateralerrorLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(IndieBrokersListLayout.createSequentialGroup()
                        .addGap(0, 8, Short.MAX_VALUE)
                        .addComponent(BrokerListTable, javax.swing.GroupLayout.PREFERRED_SIZE, 675, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, IndieBrokersListLayout.createSequentialGroup()
                        .addGap(111, 111, 111)
                        .addComponent(AddButton, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(68, 68, 68)
                        .addComponent(UpdateButton, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(56, 56, 56)
                        .addComponent(DltButton, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(7, Short.MAX_VALUE))
        );
        IndieBrokersListLayout.setVerticalGroup(
            IndieBrokersListLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(IndieBrokersListLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblTblStudentTitle)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(IndieBrokersListLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(IndieBrokersListLayout.createSequentialGroup()
                        .addGap(11, 11, 11)
                        .addComponent(BrokerListTable, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(35, 35, 35)
                        .addGroup(IndieBrokersListLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(IndieBrokersListLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(IndieBrokersListLayout.createSequentialGroup()
                                    .addGroup(IndieBrokersListLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(jLabel2)
                                        .addComponent(jLabel3))
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addGroup(IndieBrokersListLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(BrokerIDfield, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(BrokerNameField, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGroup(IndieBrokersListLayout.createSequentialGroup()
                                    .addComponent(jLabel4)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(ContactField, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(IndieBrokersListLayout.createSequentialGroup()
                                .addComponent(jLabel5)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(BankField, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(IndieBrokersListLayout.createSequentialGroup()
                                .addGroup(IndieBrokersListLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel21)
                                    .addComponent(jLabel23))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(IndieBrokersListLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(CollateralField, javax.swing.GroupLayout.DEFAULT_SIZE, 30, Short.MAX_VALUE)
                                    .addComponent(ExperienceTextFields, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(IndieBrokersListLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(CollateralerrorLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 21, Short.MAX_VALUE)
                            .addComponent(ExperienceerrorLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(BankNameerrorLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(BrokerNameerrorLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(BrokerIDerrorLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(ContacterrorLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 201, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(IndieBrokersListLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(AddButton)
                    .addComponent(UpdateButton)
                    .addComponent(DltButton))
                .addContainerGap(48, Short.MAX_VALUE))
        );

        tabPaneMain5.addTab("Admin Dashboard", IndieBrokersList);

        pnlAboutUs.setBackground(new java.awt.Color(189, 244, 255));
        pnlAboutUs.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(234, 192, 32)));

        jPanel1.setBackground(new java.awt.Color(69, 110, 181));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/IndieBrokers/resources/hero.jpg"))); // NOI18N
        jLabel1.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(18, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addComponent(jLabel1)
                .addContainerGap(16, Short.MAX_VALUE))
        );

        jLabel7.setFont(new java.awt.Font("Poppins", 1, 14)); // NOI18N
        jLabel7.setText("About Us");

        jPanel2.setBackground(new java.awt.Color(69, 110, 181));
        jPanel2.setForeground(new java.awt.Color(69, 110, 181));

        jLabel10.setBackground(new java.awt.Color(255, 255, 255));
        jLabel10.setFont(new java.awt.Font("Poppins", 1, 14)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("Name : Anshuman Kadel");

        jLabel9.setFont(new java.awt.Font("Poppins", 1, 14)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("Job : Student (part-time)");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap(9, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel10)
                        .addGap(11, 11, 11))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel9)
                        .addContainerGap())))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel10)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel9)
                .addGap(9, 9, 9))
        );

        jScrollPane2.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        jScrollPane2.setForeground(new java.awt.Color(0, 105, 255));
        jScrollPane2.setFont(new java.awt.Font("Poppins", 0, 14)); // NOI18N

        jTextArea2.setBackground(new java.awt.Color(189, 244, 255));
        jTextArea2.setColumns(20);
        jTextArea2.setFont(new java.awt.Font("Poppins", 0, 12)); // NOI18N
        jTextArea2.setForeground(new java.awt.Color(32, 64, 118));
        jTextArea2.setRows(5);
        jTextArea2.setText("At Indie Brokers, we are passionate about empowering individuals \nand businesses to succeed in today’s dynamic and ever-changing \nmarkets. Founded on the principles of innovation, integrity, and inclusivity,\n we specialize in providing tailored brokerage services designed to meet \nthe unique needs of independent thinkers and entrepreneurs.\n\nOur mission is to bridge the gap between opportunity and achievement,\noffering personalized strategies, cutting-edge tools, and expert insights \nto help our clients thrive. Whether you’re a seasoned professional or just \nstarting your journey, Indie Brokers is your trusted partner in navigating \nthe complexities of investment, real estate, and beyond.\n\nLet’s build something extraordinary – together.");
        jTextArea2.setWrapStyleWord(true);
        jScrollPane2.setViewportView(jTextArea2);

        javax.swing.GroupLayout pnlAboutUsLayout = new javax.swing.GroupLayout(pnlAboutUs);
        pnlAboutUs.setLayout(pnlAboutUsLayout);
        pnlAboutUsLayout.setHorizontalGroup(
            pnlAboutUsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlAboutUsLayout.createSequentialGroup()
                .addGap(151, 151, 151)
                .addComponent(jLabel7)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(pnlAboutUsLayout.createSequentialGroup()
                .addGap(74, 74, 74)
                .addGroup(pnlAboutUsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(pnlAboutUsLayout.createSequentialGroup()
                        .addGap(14, 14, 14)
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 459, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 31, Short.MAX_VALUE))
        );
        pnlAboutUsLayout.setVerticalGroup(
            pnlAboutUsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlAboutUsLayout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(jLabel7)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(pnlAboutUsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlAboutUsLayout.createSequentialGroup()
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 287, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(35, Short.MAX_VALUE))
        );

        tabPaneMain5.addTab("About Us", pnlAboutUs);

        javax.swing.GroupLayout IndieMainScreenLayout = new javax.swing.GroupLayout(IndieMainScreen);
        IndieMainScreen.setLayout(IndieMainScreenLayout);
        IndieMainScreenLayout.setHorizontalGroup(
            IndieMainScreenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(upperbar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(IndieMainScreenLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(tabPaneMain5, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
        );
        IndieMainScreenLayout.setVerticalGroup(
            IndieMainScreenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(IndieMainScreenLayout.createSequentialGroup()
                .addComponent(upperbar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(tabPaneMain5))
        );

        tabPaneMain5.getAccessibleContext().setAccessibleName("Broker List");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        IndieLoadingScreen.setBackground(new java.awt.Color(189, 244, 255));
        IndieLoadingScreen.setMaximumSize(new java.awt.Dimension(809, 495));
        IndieLoadingScreen.setMinimumSize(new java.awt.Dimension(809, 495));
        IndieLoadingScreen.setPreferredSize(new java.awt.Dimension(809, 495));

        jLabel18.setBackground(new java.awt.Color(0, 155, 255));
        jLabel18.setFont(new java.awt.Font("Poppins Medium", 0, 150)); // NOI18N
        jLabel18.setForeground(new java.awt.Color(0, 155, 255));
        jLabel18.setText("Indie");

        jLabel19.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/IndieBrokers/resources/logo (4).png"))); // NOI18N

        jLabel20.setFont(new java.awt.Font("Poppins Medium", 0, 36)); // NOI18N
        jLabel20.setForeground(new java.awt.Color(72, 141, 203));
        jLabel20.setText("Invest In Everything");

        pgBarSplashScreen.setStringPainted(true);
        pgBarSplashScreen.setForeground(new java.awt.Color(0, 0, 0));

        javax.swing.GroupLayout IndieLoadingScreenLayout = new javax.swing.GroupLayout(IndieLoadingScreen);
        IndieLoadingScreen.setLayout(IndieLoadingScreenLayout);
        IndieLoadingScreenLayout.setHorizontalGroup(
            IndieLoadingScreenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, IndieLoadingScreenLayout.createSequentialGroup()
                .addContainerGap(184, Short.MAX_VALUE)
                .addGroup(IndieLoadingScreenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(pgBarSplashScreen, javax.swing.GroupLayout.PREFERRED_SIZE, 476, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(IndieLoadingScreenLayout.createSequentialGroup()
                        .addComponent(jLabel19)
                        .addGap(18, 18, 18)
                        .addGroup(IndieLoadingScreenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel18)
                            .addGroup(IndieLoadingScreenLayout.createSequentialGroup()
                                .addGap(6, 6, 6)
                                .addComponent(jLabel20)))))
                .addGap(147, 147, 147))
        );
        IndieLoadingScreenLayout.setVerticalGroup(
            IndieLoadingScreenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(IndieLoadingScreenLayout.createSequentialGroup()
                .addGap(91, 91, 91)
                .addGroup(IndieLoadingScreenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(IndieLoadingScreenLayout.createSequentialGroup()
                        .addGap(11, 11, 11)
                        .addComponent(jLabel18, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel20))
                    .addComponent(jLabel19))
                .addGap(38, 38, 38)
                .addComponent(pgBarSplashScreen, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(113, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(IndieLoadingScreen, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(IndieLoadingScreen, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

     private void initializeLayout() {
        cardLayout = new java.awt.CardLayout();
        getContentPane().setLayout(cardLayout);

        // Add panels with unique identifiers
        getContentPane().add(IndieLoadingScreen, "LoadingScreen");
        getContentPane().add(IndieLoginScreen, "LoginScreen");
        getContentPane().add(IndieMainScreen, "MainScreen");

        // Start with the loading screen
        loadScreen("LoadingScreen");
    }
     
   
    private void initializeData() {
        BrokersList = new LinkedList<>();

        // Registering sample students
        registerBrokers(new IndieBrokersModel(1111, "Imperial Securities", "nabil", "9860898172", (short) 10000, 10));
        registerBrokers(new IndieBrokersModel(0001, "Agrawal Securities", "nabil", "9860898172", (short) 1001, 21));
    }

    /**
     * Simulates the loading progress using a SwingWorker thread. Updates a
     * progress bar incrementally and switches to the login screen upon
     * completion.
     */
    
    private void startProgress() {
        javax.swing.SwingWorker<Void, Integer> worker = new javax.swing.SwingWorker<>() {
            @Override
            protected Void doInBackground() throws Exception {
                for (int i = 0; i <= 100; i++) {
                    Thread.sleep(10); // Simulated delay for progress bar
                    publish(i); // Publish progress
                }
                return null;
            }

            @Override
            protected void process(java.util.List<Integer> chunks) {
                int progress = chunks.get(chunks.size() - 1);
                pgBarSplashScreen.setValue(progress);
            }

            @Override
            protected void done() {
                loadScreen("LoginScreen"); // Switch to login screen
            }
        };
        worker.execute(); // Start the worker thread
    }
    
    private void registerBrokers(IndieBrokersModel Brokers) {
        BrokersList.add(Brokers);
        DefaultTableModel model = (DefaultTableModel) BrokerTable.getModel();
        model.addRow(new Object[]{
            Brokers.getBrokerID(), Brokers.getBrokername(), Brokers.getBankName(),
            Brokers.getCollateral(), Brokers.getContact(), Brokers.getExperience()
        });
    }
    
    private void loadScreen(String screenName) {
        cardLayout.show(getContentPane(), screenName);
    }
    
    
    private void UsernameFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_UsernameFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_UsernameFieldActionPerformed

    private void LoginButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LoginButtonActionPerformed
    // Get the username and password input
        String username = UsernameField.getText();
        String password = new String(PasswordField.getPassword());

        // Check if username or password is empty
        if (username.isEmpty() || password.isEmpty()) {
            loginErrorLabel.setText("Please enter your username and password.");
        } // Check if username and password are incorrect
        else if (!username.equals("ampho") || !password.equals("ampho123")) {
            loginErrorLabel.setText("Username and password mismatch.");
        } // If credentials are correct, proceed to load the main screen
        else {
            loginErrorLabel.setText(""); // Clear any previous error messages
            loadScreen("MainScreen"); // Load the main screen
        }
    }//GEN-LAST:event_LoginButtonActionPerformed

    private void LogoutButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LogoutButtonActionPerformed
        UsernameField.setText("");
        PasswordField.setText("");
        loadScreen("LoginScreen"); // Load the main screen
    }//GEN-LAST:event_LogoutButtonActionPerformed

    private void PasswordFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PasswordFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_PasswordFieldActionPerformed

    private void AddButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AddButtonActionPerformed
        boolean isValid = true;

        // Validate Broker ID
        isValid &= validateBrokerField(
            BrokerIDfield, "", BrokerIDerrorLabel, "Must be a 4-digit number.",
            errorColor, yellowColor, ValidationUtil.isValidbrokerID(BrokerIDfield.getText())
        );

        // Validate Full Name
        isValid &= validateBrokerField(
            BrokerNameField, "", BrokerNameerrorLabel, "Must contain only alphabets.",
            errorColor, yellowColor, ValidationUtil.isValidbroker(BrokerNameField.getText())
        );

        // Validate Broker Field
        isValid &= validateBrokerField(
            BankField, "", BankNameerrorLabel, "Select global, nabil or siddhartha.",
            errorColor, yellowColor, ValidationUtil.isValidBankName(BankField.getText())
        );

        // Validate Contact
        isValid &= validateBrokerField(
            ContactField, "", ContacterrorLabel, "Must start with 98 and have 10 digits.",
            errorColor, yellowColor, ValidationUtil.isValidContact(ContactField.getText())
        );

        isValid &= validateBrokerField(
            ExperienceTextFields, "", ExperienceerrorLabel, "Must be from 1-99 years",
            errorColor, yellowColor, ValidationUtil.isValidexperience(ExperienceTextFields.getText())
        );

        

        try {
            short collateral = Short.parseShort(CollateralField.getText().trim());
            isValid &= validateBrokerField(
                CollateralField, "", CollateralerrorLabel, "Must be between 1000 and 5000000.",
                errorColor, yellowColor, ValidationUtil.isValidCollateral(collateral)
            );
        } catch (NumberFormatException e) {
            validateBrokerField(CollateralField, "", CollateralerrorLabel, "Must be a valid number.", errorColor, yellowColor, false);
            isValid = false;
        }

        if (isValid) {
            IndieBrokersModel newBroker = new IndieBrokersModel(
                Integer.parseInt(BrokerIDfield.getText().trim()),
                BrokerNameField.getText().trim(),
                BankField.getText().trim(),
                ContactField.getText().trim(),
                Short.parseShort(CollateralField.getText().trim()),
                Integer.parseInt(ExperienceTextFields.getText().trim())
            );

            if (checkDuplicateBroker(newBroker)) {
                BrokerIDfield.setBorder(createTitledBorder(errorColor, ""));
                showDialogBox("Broker ID already exists.", "Duplicate Entry", JOptionPane.WARNING_MESSAGE);
            } else {
                // Add the student if no duplicate is found
                BrokersList.add(newBroker);
                ClearBroker();
                LoadListToTable();
                showDialogBox("Broker added successfully.", "Success", JOptionPane.INFORMATION_MESSAGE);
            }
        }
    }//GEN-LAST:event_AddButtonActionPerformed

    private void BankFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BankFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_BankFieldActionPerformed

    private void ContactFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ContactFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ContactFieldActionPerformed

    private void BrokerNameFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BrokerNameFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_BrokerNameFieldActionPerformed

    private void BrokerIDfieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BrokerIDfieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_BrokerIDfieldActionPerformed

    private void LoadListToTable() {
        DefaultTableModel model = (DefaultTableModel) BrokerTable.getModel();

        // Clear existing rows if needed
        model.setRowCount(0);

        // Populate the table with student data
        BrokersList.forEach(Broker -> model.addRow(new Object[]{
            Broker.getBrokerID(),
            Broker.getBrokername(),
            Broker.getBankName(),
            Broker.getContact(),
            Broker.getCollateral(),
            Broker.getExperience()
        }));
    }
    private void UpdateButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_UpdateButtonActionPerformed
        boolean isValid = true;
        
        isValid &= validateBrokerField(
            BrokerIDfield, "", BrokerIDerrorLabel, "Must be a 4-digit number.",
            errorColor, yellowColor, ValidationUtil.isValidbrokerID(BrokerIDfield.getText())
        );

        // Validate Full Name
        isValid &= validateBrokerField(
            BrokerNameField, "", BrokerNameerrorLabel, "Must contain only alphabets.",
            errorColor, yellowColor, ValidationUtil.isValidbroker(BrokerNameField.getText())
        );

        // Validate bank
        isValid &= validateBrokerField(
            BankField, "", BankNameerrorLabel, "Select nabil, global or siddhartha.",
            errorColor, yellowColor, ValidationUtil.isValidBankName(BankField.getText())
        );

        // Validate Contact
        isValid &= validateBrokerField(
            ContactField, "", ContacterrorLabel, "Must start with 98 and have 10 digits.",
            errorColor, yellowColor, ValidationUtil.isValidContact(ContactField.getText())
        );

        
        
        try{
            String expe = ExperienceTextFields.getText().trim();
            isValid &= validateBrokerField(
                    ExperienceTextFields, "", ExperienceerrorLabel, "Must be 5-25 Years,",
                    errorColor, yellowColor, ValidationUtil.isValidexperience(expe)
            );
        }
        catch(NumberFormatException e){
            validateBrokerField(ExperienceTextFields, "", ExperienceerrorLabel, "Must be valid Number", errorColor, yellowColor, false);
            isValid = false;
        }
        
        try {
            short collateral = Short.parseShort(CollateralField.getText().trim());
            isValid &= validateBrokerField(
                CollateralField, "", CollateralerrorLabel, "Must be greater than 1000.",
                errorColor, yellowColor, ValidationUtil.isValidCollateral(collateral)
            );
        } catch (NumberFormatException e) {
            validateBrokerField(CollateralField, "", CollateralerrorLabel, "Must be a valid number.", errorColor, yellowColor, false);
            isValid = false;
        }
        
        if(isValid){
            int BrokerID = Integer.parseInt(BrokerIDfield.getText().trim());
            IndieBrokersModel Indie = BrokersList.stream()
                    .filter(broker -> broker.getBrokerID() == BrokerID)
                    .findFirst()
                    .orElse(null);
            
            if(Indie == null){
                BrokerIDfield.setBorder(createTitledBorder(errorColor, "Broker ID"));
                showDialogBox("Broker ID not found.Please provide a Valid ID", "Invalid Input", JOptionPane.WARNING_MESSAGE);
            }
            
            else{
                Indie.setBrokername(BrokerNameField.getText().trim());
                Indie.setBrokerID(Integer.parseInt(BrokerIDfield.getText().trim()));
                Indie.setBankName(BankField.getText().trim());
                Indie.setContact(ContactField.getText().trim());
                Indie.setCollateral(Short.parseShort(CollateralField.getText().trim()));
                Indie.setExperience(Integer.parseInt(ExperienceTextFields.getText().trim()));
                
                LoadListToTable();
                showDialogBox("Broker Added Successfully.", "Success", JOptionPane.INFORMATION_MESSAGE);
                ClearBroker();
                BrokerIDfield.setBorder(createTitledBorder(yellowColor, "Broker ID"));
                
            }
        }
    }//GEN-LAST:event_UpdateButtonActionPerformed

    private void DltButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DltButtonActionPerformed
        String brokerid = BrokerIDfield.getText().trim();
        if (brokerid.isEmpty()){
            JOptionPane.showMessageDialog(null, "Enter Broker ID you want to delete", "Empty ID Field", JOptionPane.INFORMATION_MESSAGE);
            return;
            
        }
        
        IndieBrokersModel exists = null ;
        for (IndieBrokersModel broker : BrokersList){
            if(broker.getBrokerID() == Integer.parseInt (brokerid)){
                exists = broker;
                break;
       
            }
        }
        if (exists == null){
            JOptionPane.showMessageDialog(null, "Please Enter valid ID", "Invalid ID!!", JOptionPane.INFORMATION_MESSAGE);
            return;
        }
        
        BrokersList.remove(exists);
        JOptionPane.showMessageDialog(null, "Broker has been removed", "Its Deleted", JOptionPane.INFORMATION_MESSAGE);
        
        LoadListToTable();
        ClearBroker();
    }//GEN-LAST:event_DltButtonActionPerformed

    
    
    private boolean validateBrokerField(JTextField textField, String fieldName, JLabel errorLbl, String errorMsg, Color errorColor, Color successColor, boolean isValidFormat) {
        if (ValidationUtil.isNullOrEmpty(textField.getText())) {
            textField.setBorder(createTitledBorder(errorColor, fieldName));
            errorLbl.setText("Field cannot be empty!");
            errorLbl.setVisible(true);
            return false;
        } else if (!isValidFormat) {
            textField.setBorder(createTitledBorder(errorColor, fieldName));
            errorLbl.setText(errorMsg);
            errorLbl.setVisible(true);
            return false;
        } else {
            textField.setBorder(createTitledBorder(successColor, fieldName));
            errorLbl.setVisible(false);
            return true;
        }
    }
    
    private javax.swing.border.TitledBorder createTitledBorder(Color color, String title) {
        return javax.swing.BorderFactory.createTitledBorder(
                javax.swing.BorderFactory.createLineBorder(color, 2),
                title,
                javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION,
                javax.swing.border.TitledBorder.DEFAULT_POSITION
        );
    }
    
    private void showDialogBox(String message, String title, int messageType) {
        JOptionPane.showMessageDialog(this, message, title, messageType);
    }
    
    private void ClearBroker() {
        BrokerIDfield.setText("");
        BrokerNameField.setText("");
        BankField.setText("");
        ContactField.setText("");
        CollateralField.setText("");
        ExperienceTextFields.setText("");
        
    }
    
    private boolean checkDuplicateBroker(IndieBrokersModel Broker) {
        return BrokersList.stream()
                .anyMatch(existingBroker
                        -> existingBroker.getBrokerID() == Broker.getBrokerID());
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(IndieBrokersApp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(IndieBrokersApp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(IndieBrokersApp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(IndieBrokersApp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new IndieBrokersApp().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton AddButton;
    private javax.swing.JTextField BankField;
    private javax.swing.JLabel BankNameerrorLabel;
    private javax.swing.JLabel BrokerIDerrorLabel;
    private javax.swing.JTextField BrokerIDfield;
    private javax.swing.JScrollPane BrokerListTable;
    private javax.swing.JTextField BrokerNameField;
    private javax.swing.JLabel BrokerNameerrorLabel;
    private javax.swing.JTable BrokerTable;
    private javax.swing.JTextField CollateralField;
    private javax.swing.JLabel CollateralerrorLabel;
    private javax.swing.JTextField ContactField;
    private javax.swing.JLabel ContacterrorLabel;
    private javax.swing.JButton DltButton;
    private javax.swing.JTextField ExperienceTextFields;
    private javax.swing.JLabel ExperienceerrorLabel;
    private javax.swing.JPanel IndieBrokersList;
    private javax.swing.JPanel IndieLoadingScreen;
    private javax.swing.JPanel IndieLoginScreen;
    private javax.swing.JPanel IndieMainScreen;
    private javax.swing.JButton LoginButton;
    private javax.swing.JButton LogoutButton;
    private javax.swing.JPasswordField PasswordField;
    private javax.swing.JButton UpdateButton;
    private javax.swing.JTextField UsernameField;
    private javax.swing.JLabel indienamelbl;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextArea jTextArea2;
    private javax.swing.JLabel lblTblStudentTitle;
    private javax.swing.JLabel loginErrorLabel;
    private javax.swing.JLabel logolbl;
    private javax.swing.JProgressBar pgBarSplashScreen;
    private javax.swing.JPanel pnlAboutUs;
    private javax.swing.JPanel pnlHome5;
    private javax.swing.JTabbedPane tabPaneMain5;
    private javax.swing.JPanel upperbar;
    // End of variables declaration//GEN-END:variables
}
